# H2 in-memory database (for development)
# PostgreSQL via Supabase
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&preferQueryMode=simple
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.rdlqjundyuozrthywmhq
spring.datasource.password=devOpsVMS_spring
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=heythisisour_devops_project_secret_key
jwt.expiration=86400000

# App port
server.port=8082
